// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.notdot.bdbdatastore;

public final class Indexing {
  private Indexing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PropertyIndexKey extends
      com.google.protobuf.GeneratedMessage {
    // Use PropertyIndexKey.newBuilder() to construct.
    private PropertyIndexKey() {}
    
    private static final PropertyIndexKey defaultInstance = new PropertyIndexKey();
    public static PropertyIndexKey getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyIndexKey getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_PropertyIndexKey_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_PropertyIndexKey_fieldAccessorTable;
    }
    
    // required bytes kind = 1;
    private boolean hasKind;
    private com.google.protobuf.ByteString kind_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKind() { return hasKind; }
    public com.google.protobuf.ByteString getKind() { return kind_; }
    
    // required bytes name = 2;
    private boolean hasName;
    private com.google.protobuf.ByteString name_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasName() { return hasName; }
    public com.google.protobuf.ByteString getName() { return name_; }
    
    // required .com.google.appengine.entity.PropertyValue value = 3;
    private boolean hasValue;
    private com.google.appengine.entity.Entity.PropertyValue value_ = com.google.appengine.entity.Entity.PropertyValue.getDefaultInstance();
    public boolean hasValue() { return hasValue; }
    public com.google.appengine.entity.Entity.PropertyValue getValue() { return value_; }
    
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.notdot.bdbdatastore.Indexing.PropertyIndexKey prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.notdot.bdbdatastore.Indexing.PropertyIndexKey.newBuilder()
      private Builder() {}
      
      net.notdot.bdbdatastore.Indexing.PropertyIndexKey result = new net.notdot.bdbdatastore.Indexing.PropertyIndexKey();
      
      @Override
      protected net.notdot.bdbdatastore.Indexing.PropertyIndexKey internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.notdot.bdbdatastore.Indexing.PropertyIndexKey();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.notdot.bdbdatastore.Indexing.PropertyIndexKey.getDescriptor();
      }
      
      public net.notdot.bdbdatastore.Indexing.PropertyIndexKey getDefaultInstanceForType() {
        return net.notdot.bdbdatastore.Indexing.PropertyIndexKey.getDefaultInstance();
      }
      
      public net.notdot.bdbdatastore.Indexing.PropertyIndexKey build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.notdot.bdbdatastore.Indexing.PropertyIndexKey buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.notdot.bdbdatastore.Indexing.PropertyIndexKey buildPartial() {
        net.notdot.bdbdatastore.Indexing.PropertyIndexKey returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required bytes kind = 1;
      public boolean hasKind() {
        return result.hasKind();
      }
      public com.google.protobuf.ByteString getKind() {
        return result.getKind();
      }
      public Builder setKind(com.google.protobuf.ByteString value) {
        result.hasKind = true;
        result.kind_ = value;
        return this;
      }
      public Builder clearKind() {
        result.hasKind = false;
        result.kind_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // required bytes name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public com.google.protobuf.ByteString getName() {
        return result.getName();
      }
      public Builder setName(com.google.protobuf.ByteString value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // required .com.google.appengine.entity.PropertyValue value = 3;
      public boolean hasValue() {
        return result.hasValue();
      }
      public com.google.appengine.entity.Entity.PropertyValue getValue() {
        return result.getValue();
      }
      public Builder setValue(com.google.appengine.entity.Entity.PropertyValue value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder setValue(com.google.appengine.entity.Entity.PropertyValue.Builder builderForValue) {
        result.hasValue = true;
        result.value_ = builderForValue.build();
        return this;
      }
      public Builder mergeValue(com.google.appengine.entity.Entity.PropertyValue value) {
        if (result.hasValue() &&
            result.value_ != com.google.appengine.entity.Entity.PropertyValue.getDefaultInstance()) {
          result.value_ =
            com.google.appengine.entity.Entity.PropertyValue.newBuilder(result.value_).mergeFrom(value).buildPartial();
        } else {
          result.value_ = value;
        }
        result.hasValue = true;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = com.google.appengine.entity.Entity.PropertyValue.getDefaultInstance();
        return this;
      }
    }
    
    static {
      net.notdot.bdbdatastore.Indexing.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_notdot_bdbdatastore_PropertyIndexKey_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_notdot_bdbdatastore_PropertyIndexKey_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\016indexing.proto\022\027net.notdot.bdbdatastor" +
      "e\032\014entity.proto\032\016api_base.proto\"i\n\020Prope" +
      "rtyIndexKey\022\014\n\004kind\030\001 \002(\014\022\014\n\004name\030\002 \002(\014\022" +
      "9\n\005value\030\003 \002(\0132*.com.google.appengine.en" +
      "tity.PropertyValue";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_notdot_bdbdatastore_PropertyIndexKey_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_notdot_bdbdatastore_PropertyIndexKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_notdot_bdbdatastore_PropertyIndexKey_descriptor,
              new java.lang.String[] { "Kind", "Name", "Value", },
              net.notdot.bdbdatastore.Indexing.PropertyIndexKey.class,
              net.notdot.bdbdatastore.Indexing.PropertyIndexKey.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.appengine.entity.Entity.getDescriptor(),
          com.google.appengine.base.ApiBase.getDescriptor(),
        }, assigner);
  }
}
