// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.notdot.protorpc;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.notdot.protorpc.Rpc.internal_static_net_notdot_protorpc_Request_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.notdot.protorpc.Rpc.internal_static_net_notdot_protorpc_Request_fieldAccessorTable;
    }
    
    // required string method = 1;
    private boolean hasMethod;
    private java.lang.String method_ = "";
    public boolean hasMethod() { return hasMethod; }
    public java.lang.String getMethod() { return method_; }
    
    // required bytes body = 2;
    private boolean hasBody;
    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBody() { return hasBody; }
    public com.google.protobuf.ByteString getBody() { return body_; }
    
    public static net.notdot.protorpc.Rpc.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.notdot.protorpc.Rpc.Request prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.notdot.protorpc.Rpc.Request.newBuilder()
      private Builder() {}
      
      net.notdot.protorpc.Rpc.Request result = new net.notdot.protorpc.Rpc.Request();
      
      @Override
      protected net.notdot.protorpc.Rpc.Request internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.notdot.protorpc.Rpc.Request();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.notdot.protorpc.Rpc.Request.getDescriptor();
      }
      
      public net.notdot.protorpc.Rpc.Request getDefaultInstanceForType() {
        return net.notdot.protorpc.Rpc.Request.getDefaultInstance();
      }
      
      public net.notdot.protorpc.Rpc.Request build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.notdot.protorpc.Rpc.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.notdot.protorpc.Rpc.Request buildPartial() {
        net.notdot.protorpc.Rpc.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string method = 1;
      public boolean hasMethod() {
        return result.hasMethod();
      }
      public java.lang.String getMethod() {
        return result.getMethod();
      }
      public Builder setMethod(java.lang.String value) {
        result.hasMethod = true;
        result.method_ = value;
        return this;
      }
      public Builder clearMethod() {
        result.hasMethod = false;
        result.method_ = "";
        return this;
      }
      
      // required bytes body = 2;
      public boolean hasBody() {
        return result.hasBody();
      }
      public com.google.protobuf.ByteString getBody() {
        return result.getBody();
      }
      public Builder setBody(com.google.protobuf.ByteString value) {
        result.hasBody = true;
        result.body_ = value;
        return this;
      }
      public Builder clearBody() {
        result.hasBody = false;
        result.body_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
    }
    
    static {
      net.notdot.protorpc.Rpc.getDescriptor();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.notdot.protorpc.Rpc.internal_static_net_notdot_protorpc_Response_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.notdot.protorpc.Rpc.internal_static_net_notdot_protorpc_Response_fieldAccessorTable;
    }
    
    public static enum ResponseType {
      OK(0, 0),
      FAILED(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static ResponseType valueOf(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return FAILED;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.notdot.protorpc.Rpc.Response.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final ResponseType[] VALUES = {
        OK, FAILED, 
      };
      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private ResponseType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        net.notdot.protorpc.Rpc.getDescriptor();
      }
    }
    
    // required .net.notdot.protorpc.Response.ResponseType status = 1 [default = OK];
    private boolean hasStatus;
    private net.notdot.protorpc.Rpc.Response.ResponseType status_ = net.notdot.protorpc.Rpc.Response.ResponseType.OK;
    public boolean hasStatus() { return hasStatus; }
    public net.notdot.protorpc.Rpc.Response.ResponseType getStatus() { return status_; }
    
    // optional bytes body = 2;
    private boolean hasBody;
    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBody() { return hasBody; }
    public com.google.protobuf.ByteString getBody() { return body_; }
    
    // optional string error = 3;
    private boolean hasError;
    private java.lang.String error_ = "";
    public boolean hasError() { return hasError; }
    public java.lang.String getError() { return error_; }
    
    public static net.notdot.protorpc.Rpc.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.protorpc.Rpc.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.notdot.protorpc.Rpc.Response prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.notdot.protorpc.Rpc.Response.newBuilder()
      private Builder() {}
      
      net.notdot.protorpc.Rpc.Response result = new net.notdot.protorpc.Rpc.Response();
      
      @Override
      protected net.notdot.protorpc.Rpc.Response internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.notdot.protorpc.Rpc.Response();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.notdot.protorpc.Rpc.Response.getDescriptor();
      }
      
      public net.notdot.protorpc.Rpc.Response getDefaultInstanceForType() {
        return net.notdot.protorpc.Rpc.Response.getDefaultInstance();
      }
      
      public net.notdot.protorpc.Rpc.Response build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.notdot.protorpc.Rpc.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.notdot.protorpc.Rpc.Response buildPartial() {
        net.notdot.protorpc.Rpc.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .net.notdot.protorpc.Response.ResponseType status = 1 [default = OK];
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public net.notdot.protorpc.Rpc.Response.ResponseType getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(net.notdot.protorpc.Rpc.Response.ResponseType value) {
        result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = net.notdot.protorpc.Rpc.Response.ResponseType.OK;
        return this;
      }
      
      // optional bytes body = 2;
      public boolean hasBody() {
        return result.hasBody();
      }
      public com.google.protobuf.ByteString getBody() {
        return result.getBody();
      }
      public Builder setBody(com.google.protobuf.ByteString value) {
        result.hasBody = true;
        result.body_ = value;
        return this;
      }
      public Builder clearBody() {
        result.hasBody = false;
        result.body_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // optional string error = 3;
      public boolean hasError() {
        return result.hasError();
      }
      public java.lang.String getError() {
        return result.getError();
      }
      public Builder setError(java.lang.String value) {
        result.hasError = true;
        result.error_ = value;
        return this;
      }
      public Builder clearError() {
        result.hasError = false;
        result.error_ = "";
        return this;
      }
    }
    
    static {
      net.notdot.protorpc.Rpc.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_notdot_protorpc_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_notdot_protorpc_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_notdot_protorpc_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_notdot_protorpc_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\trpc.proto\022\023net.notdot.protorpc\"\'\n\007Requ" +
      "est\022\016\n\006method\030\001 \002(\t\022\014\n\004body\030\002 \002(\014\"\213\001\n\010Re" +
      "sponse\022>\n\006status\030\001 \002(\0162*.net.notdot.prot" +
      "orpc.Response.ResponseType:\002OK\022\014\n\004body\030\002" +
      " \001(\014\022\r\n\005error\030\003 \001(\t\"\"\n\014ResponseType\022\006\n\002O" +
      "K\020\000\022\n\n\006FAILED\020\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_notdot_protorpc_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_notdot_protorpc_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_notdot_protorpc_Request_descriptor,
              new java.lang.String[] { "Method", "Body", },
              net.notdot.protorpc.Rpc.Request.class,
              net.notdot.protorpc.Rpc.Request.Builder.class);
          internal_static_net_notdot_protorpc_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_notdot_protorpc_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_notdot_protorpc_Response_descriptor,
              new java.lang.String[] { "Status", "Body", "Error", },
              net.notdot.protorpc.Rpc.Response.class,
              net.notdot.protorpc.Rpc.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
