// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.appengine.base;

public final class ApiBase {
  private ApiBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class StringProto extends
      com.google.protobuf.GeneratedMessage {
    // Use StringProto.newBuilder() to construct.
    private StringProto() {}
    
    private static final StringProto defaultInstance = new StringProto();
    public static StringProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public StringProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_StringProto_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_StringProto_fieldAccessorTable;
    }
    
    // required string value = 1;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    public static com.google.appengine.base.ApiBase.StringProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.StringProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.StringProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.StringProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.StringProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.StringProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.StringProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.StringProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.google.appengine.base.ApiBase.StringProto prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.google.appengine.base.ApiBase.StringProto.newBuilder()
      private Builder() {}
      
      com.google.appengine.base.ApiBase.StringProto result = new com.google.appengine.base.ApiBase.StringProto();
      
      @Override
      protected com.google.appengine.base.ApiBase.StringProto internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.google.appengine.base.ApiBase.StringProto();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appengine.base.ApiBase.StringProto.getDescriptor();
      }
      
      public com.google.appengine.base.ApiBase.StringProto getDefaultInstanceForType() {
        return com.google.appengine.base.ApiBase.StringProto.getDefaultInstance();
      }
      
      public com.google.appengine.base.ApiBase.StringProto build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.google.appengine.base.ApiBase.StringProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.appengine.base.ApiBase.StringProto buildPartial() {
        com.google.appengine.base.ApiBase.StringProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = "";
        return this;
      }
    }
    
    static {
      com.google.appengine.base.ApiBase.getDescriptor();
    }
  }
  
  public static final class Integer32Proto extends
      com.google.protobuf.GeneratedMessage {
    // Use Integer32Proto.newBuilder() to construct.
    private Integer32Proto() {}
    
    private static final Integer32Proto defaultInstance = new Integer32Proto();
    public static Integer32Proto getDefaultInstance() {
      return defaultInstance;
    }
    
    public Integer32Proto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_Integer32Proto_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_Integer32Proto_fieldAccessorTable;
    }
    
    // required int32 value = 1;
    private boolean hasValue;
    private int value_ = 0;
    public boolean hasValue() { return hasValue; }
    public int getValue() { return value_; }
    
    public static com.google.appengine.base.ApiBase.Integer32Proto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer32Proto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer32Proto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer32Proto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer32Proto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer32Proto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer32Proto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer32Proto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.google.appengine.base.ApiBase.Integer32Proto prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.google.appengine.base.ApiBase.Integer32Proto.newBuilder()
      private Builder() {}
      
      com.google.appengine.base.ApiBase.Integer32Proto result = new com.google.appengine.base.ApiBase.Integer32Proto();
      
      @Override
      protected com.google.appengine.base.ApiBase.Integer32Proto internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.google.appengine.base.ApiBase.Integer32Proto();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appengine.base.ApiBase.Integer32Proto.getDescriptor();
      }
      
      public com.google.appengine.base.ApiBase.Integer32Proto getDefaultInstanceForType() {
        return com.google.appengine.base.ApiBase.Integer32Proto.getDefaultInstance();
      }
      
      public com.google.appengine.base.ApiBase.Integer32Proto build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.google.appengine.base.ApiBase.Integer32Proto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.appengine.base.ApiBase.Integer32Proto buildPartial() {
        com.google.appengine.base.ApiBase.Integer32Proto returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int32 value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public int getValue() {
        return result.getValue();
      }
      public Builder setValue(int value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = 0;
        return this;
      }
    }
    
    static {
      com.google.appengine.base.ApiBase.getDescriptor();
    }
  }
  
  public static final class Integer64Proto extends
      com.google.protobuf.GeneratedMessage {
    // Use Integer64Proto.newBuilder() to construct.
    private Integer64Proto() {}
    
    private static final Integer64Proto defaultInstance = new Integer64Proto();
    public static Integer64Proto getDefaultInstance() {
      return defaultInstance;
    }
    
    public Integer64Proto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_Integer64Proto_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_Integer64Proto_fieldAccessorTable;
    }
    
    // required int64 value = 1;
    private boolean hasValue;
    private long value_ = 0L;
    public boolean hasValue() { return hasValue; }
    public long getValue() { return value_; }
    
    public static com.google.appengine.base.ApiBase.Integer64Proto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer64Proto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer64Proto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer64Proto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer64Proto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer64Proto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer64Proto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.Integer64Proto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.google.appengine.base.ApiBase.Integer64Proto prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.google.appengine.base.ApiBase.Integer64Proto.newBuilder()
      private Builder() {}
      
      com.google.appengine.base.ApiBase.Integer64Proto result = new com.google.appengine.base.ApiBase.Integer64Proto();
      
      @Override
      protected com.google.appengine.base.ApiBase.Integer64Proto internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.google.appengine.base.ApiBase.Integer64Proto();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appengine.base.ApiBase.Integer64Proto.getDescriptor();
      }
      
      public com.google.appengine.base.ApiBase.Integer64Proto getDefaultInstanceForType() {
        return com.google.appengine.base.ApiBase.Integer64Proto.getDefaultInstance();
      }
      
      public com.google.appengine.base.ApiBase.Integer64Proto build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.google.appengine.base.ApiBase.Integer64Proto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.appengine.base.ApiBase.Integer64Proto buildPartial() {
        com.google.appengine.base.ApiBase.Integer64Proto returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int64 value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public long getValue() {
        return result.getValue();
      }
      public Builder setValue(long value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = 0L;
        return this;
      }
    }
    
    static {
      com.google.appengine.base.ApiBase.getDescriptor();
    }
  }
  
  public static final class BoolProto extends
      com.google.protobuf.GeneratedMessage {
    // Use BoolProto.newBuilder() to construct.
    private BoolProto() {}
    
    private static final BoolProto defaultInstance = new BoolProto();
    public static BoolProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public BoolProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_BoolProto_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_BoolProto_fieldAccessorTable;
    }
    
    // required bool value = 1;
    private boolean hasValue;
    private boolean value_ = false;
    public boolean hasValue() { return hasValue; }
    public boolean getValue() { return value_; }
    
    public static com.google.appengine.base.ApiBase.BoolProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.BoolProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.BoolProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.BoolProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.BoolProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.BoolProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.BoolProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.BoolProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.google.appengine.base.ApiBase.BoolProto prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.google.appengine.base.ApiBase.BoolProto.newBuilder()
      private Builder() {}
      
      com.google.appengine.base.ApiBase.BoolProto result = new com.google.appengine.base.ApiBase.BoolProto();
      
      @Override
      protected com.google.appengine.base.ApiBase.BoolProto internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.google.appengine.base.ApiBase.BoolProto();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appengine.base.ApiBase.BoolProto.getDescriptor();
      }
      
      public com.google.appengine.base.ApiBase.BoolProto getDefaultInstanceForType() {
        return com.google.appengine.base.ApiBase.BoolProto.getDefaultInstance();
      }
      
      public com.google.appengine.base.ApiBase.BoolProto build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.google.appengine.base.ApiBase.BoolProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.appengine.base.ApiBase.BoolProto buildPartial() {
        com.google.appengine.base.ApiBase.BoolProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required bool value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public boolean getValue() {
        return result.getValue();
      }
      public Builder setValue(boolean value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = false;
        return this;
      }
    }
    
    static {
      com.google.appengine.base.ApiBase.getDescriptor();
    }
  }
  
  public static final class DoubleProto extends
      com.google.protobuf.GeneratedMessage {
    // Use DoubleProto.newBuilder() to construct.
    private DoubleProto() {}
    
    private static final DoubleProto defaultInstance = new DoubleProto();
    public static DoubleProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public DoubleProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_DoubleProto_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_DoubleProto_fieldAccessorTable;
    }
    
    // required double value = 1;
    private boolean hasValue;
    private double value_ = 0D;
    public boolean hasValue() { return hasValue; }
    public double getValue() { return value_; }
    
    public static com.google.appengine.base.ApiBase.DoubleProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.DoubleProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.DoubleProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.DoubleProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.DoubleProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.DoubleProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.DoubleProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.DoubleProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.google.appengine.base.ApiBase.DoubleProto prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.google.appengine.base.ApiBase.DoubleProto.newBuilder()
      private Builder() {}
      
      com.google.appengine.base.ApiBase.DoubleProto result = new com.google.appengine.base.ApiBase.DoubleProto();
      
      @Override
      protected com.google.appengine.base.ApiBase.DoubleProto internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.google.appengine.base.ApiBase.DoubleProto();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appengine.base.ApiBase.DoubleProto.getDescriptor();
      }
      
      public com.google.appengine.base.ApiBase.DoubleProto getDefaultInstanceForType() {
        return com.google.appengine.base.ApiBase.DoubleProto.getDefaultInstance();
      }
      
      public com.google.appengine.base.ApiBase.DoubleProto build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.google.appengine.base.ApiBase.DoubleProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.appengine.base.ApiBase.DoubleProto buildPartial() {
        com.google.appengine.base.ApiBase.DoubleProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required double value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public double getValue() {
        return result.getValue();
      }
      public Builder setValue(double value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = 0D;
        return this;
      }
    }
    
    static {
      com.google.appengine.base.ApiBase.getDescriptor();
    }
  }
  
  public static final class VoidProto extends
      com.google.protobuf.GeneratedMessage {
    // Use VoidProto.newBuilder() to construct.
    private VoidProto() {}
    
    private static final VoidProto defaultInstance = new VoidProto();
    public static VoidProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public VoidProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_VoidProto_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appengine.base.ApiBase.internal_static_com_google_appengine_base_VoidProto_fieldAccessorTable;
    }
    
    public static com.google.appengine.base.ApiBase.VoidProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.VoidProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.VoidProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.VoidProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.VoidProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.VoidProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.appengine.base.ApiBase.VoidProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.appengine.base.ApiBase.VoidProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.google.appengine.base.ApiBase.VoidProto prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.google.appengine.base.ApiBase.VoidProto.newBuilder()
      private Builder() {}
      
      com.google.appengine.base.ApiBase.VoidProto result = new com.google.appengine.base.ApiBase.VoidProto();
      
      @Override
      protected com.google.appengine.base.ApiBase.VoidProto internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.google.appengine.base.ApiBase.VoidProto();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appengine.base.ApiBase.VoidProto.getDescriptor();
      }
      
      public com.google.appengine.base.ApiBase.VoidProto getDefaultInstanceForType() {
        return com.google.appengine.base.ApiBase.VoidProto.getDefaultInstance();
      }
      
      public com.google.appengine.base.ApiBase.VoidProto build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.google.appengine.base.ApiBase.VoidProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.appengine.base.ApiBase.VoidProto buildPartial() {
        com.google.appengine.base.ApiBase.VoidProto returnMe = result;
        result = null;
        return returnMe;
      }
      
    }
    
    static {
      com.google.appengine.base.ApiBase.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_appengine_base_StringProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_appengine_base_StringProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_appengine_base_Integer32Proto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_appengine_base_Integer32Proto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_appengine_base_Integer64Proto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_appengine_base_Integer64Proto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_appengine_base_BoolProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_appengine_base_BoolProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_appengine_base_DoubleProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_appengine_base_DoubleProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_appengine_base_VoidProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_appengine_base_VoidProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\016api_base.proto\022\031com.google.appengine.b" +
      "ase\"\034\n\013StringProto\022\r\n\005value\030\001 \002(\t\"\037\n\016Int" +
      "eger32Proto\022\r\n\005value\030\001 \002(\005\"\037\n\016Integer64P" +
      "roto\022\r\n\005value\030\001 \002(\003\"\032\n\tBoolProto\022\r\n\005valu" +
      "e\030\001 \002(\010\"\034\n\013DoubleProto\022\r\n\005value\030\001 \002(\001\"\013\n" +
      "\tVoidProto";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_google_appengine_base_StringProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_google_appengine_base_StringProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_google_appengine_base_StringProto_descriptor,
              new java.lang.String[] { "Value", },
              com.google.appengine.base.ApiBase.StringProto.class,
              com.google.appengine.base.ApiBase.StringProto.Builder.class);
          internal_static_com_google_appengine_base_Integer32Proto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_google_appengine_base_Integer32Proto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_google_appengine_base_Integer32Proto_descriptor,
              new java.lang.String[] { "Value", },
              com.google.appengine.base.ApiBase.Integer32Proto.class,
              com.google.appengine.base.ApiBase.Integer32Proto.Builder.class);
          internal_static_com_google_appengine_base_Integer64Proto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_google_appengine_base_Integer64Proto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_google_appengine_base_Integer64Proto_descriptor,
              new java.lang.String[] { "Value", },
              com.google.appengine.base.ApiBase.Integer64Proto.class,
              com.google.appengine.base.ApiBase.Integer64Proto.Builder.class);
          internal_static_com_google_appengine_base_BoolProto_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_google_appengine_base_BoolProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_google_appengine_base_BoolProto_descriptor,
              new java.lang.String[] { "Value", },
              com.google.appengine.base.ApiBase.BoolProto.class,
              com.google.appengine.base.ApiBase.BoolProto.Builder.class);
          internal_static_com_google_appengine_base_DoubleProto_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_google_appengine_base_DoubleProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_google_appengine_base_DoubleProto_descriptor,
              new java.lang.String[] { "Value", },
              com.google.appengine.base.ApiBase.DoubleProto.class,
              com.google.appengine.base.ApiBase.DoubleProto.Builder.class);
          internal_static_com_google_appengine_base_VoidProto_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_google_appengine_base_VoidProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_google_appengine_base_VoidProto_descriptor,
              new java.lang.String[] { },
              com.google.appengine.base.ApiBase.VoidProto.class,
              com.google.appengine.base.ApiBase.VoidProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
