#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_RESPONSE_RESPONSETYPE = descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='net.notdot.protorpc.Response.ResponseType',
  filename='ResponseType',
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_FAILED', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CALL_NOT_FOUND', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARGUMENT_ERROR', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEADLINE_EXCEEDED', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CANCELLED', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='APPLICATION_ERROR', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OTHER_ERROR', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OVER_QUOTA', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_TOO_LARGE', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CAPABILITY_DISABLED', index=10, number=10,
      options=None,
      type=None),
  ],
  options=None,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='net.notdot.protorpc.Request',
  filename='rpc.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rpc_id', full_name='net.notdot.protorpc.Request.rpc_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='service', full_name='net.notdot.protorpc.Request.service', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='method', full_name='net.notdot.protorpc.Request.method', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='body', full_name='net.notdot.protorpc.Request.body', index=3,
      number=4, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='net.notdot.protorpc.Response',
  filename='rpc.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rpc_id', full_name='net.notdot.protorpc.Response.rpc_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='net.notdot.protorpc.Response.status', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='body', full_name='net.notdot.protorpc.Response.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_detail', full_name='net.notdot.protorpc.Response.error_detail', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='application_error', full_name='net.notdot.protorpc.Response.application_error', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _RESPONSE_RESPONSETYPE,
  ],
  options=None)


_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_RESPONSETYPE

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE

