// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.notdot.bdbdatastore;

public final class Indexing {
  private Indexing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class EntityData extends
      com.google.protobuf.GeneratedMessage {
    // Use EntityData.newBuilder() to construct.
    private EntityData() {}
    
    private static final EntityData defaultInstance = new EntityData();
    public static EntityData getDefaultInstance() {
      return defaultInstance;
    }
    
    public EntityData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_EntityData_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_EntityData_fieldAccessorTable;
    }
    
    // required .com.google.appengine.entity.EntityProto data = 1;
    private boolean hasData;
    private com.google.appengine.entity.Entity.EntityProto data_ = com.google.appengine.entity.Entity.EntityProto.getDefaultInstance();
    public boolean hasData() { return hasData; }
    public com.google.appengine.entity.Entity.EntityProto getData() { return data_; }
    
    // required int64 update_id = 2;
    private boolean hasUpdateId;
    private long updateId_ = 0L;
    public boolean hasUpdateId() { return hasUpdateId; }
    public long getUpdateId() { return updateId_; }
    
    public static net.notdot.bdbdatastore.Indexing.EntityData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.notdot.bdbdatastore.Indexing.EntityData prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.notdot.bdbdatastore.Indexing.EntityData.newBuilder()
      private Builder() {}
      
      net.notdot.bdbdatastore.Indexing.EntityData result = new net.notdot.bdbdatastore.Indexing.EntityData();
      
      @Override
      protected net.notdot.bdbdatastore.Indexing.EntityData internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.notdot.bdbdatastore.Indexing.EntityData();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.notdot.bdbdatastore.Indexing.EntityData.getDescriptor();
      }
      
      public net.notdot.bdbdatastore.Indexing.EntityData getDefaultInstanceForType() {
        return net.notdot.bdbdatastore.Indexing.EntityData.getDefaultInstance();
      }
      
      public net.notdot.bdbdatastore.Indexing.EntityData build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.notdot.bdbdatastore.Indexing.EntityData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.notdot.bdbdatastore.Indexing.EntityData buildPartial() {
        net.notdot.bdbdatastore.Indexing.EntityData returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .com.google.appengine.entity.EntityProto data = 1;
      public boolean hasData() {
        return result.hasData();
      }
      public com.google.appengine.entity.Entity.EntityProto getData() {
        return result.getData();
      }
      public Builder setData(com.google.appengine.entity.Entity.EntityProto value) {
        result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder setData(com.google.appengine.entity.Entity.EntityProto.Builder builderForValue) {
        result.hasData = true;
        result.data_ = builderForValue.build();
        return this;
      }
      public Builder mergeData(com.google.appengine.entity.Entity.EntityProto value) {
        if (result.hasData() &&
            result.data_ != com.google.appengine.entity.Entity.EntityProto.getDefaultInstance()) {
          result.data_ =
            com.google.appengine.entity.Entity.EntityProto.newBuilder(result.data_).mergeFrom(value).buildPartial();
        } else {
          result.data_ = value;
        }
        result.hasData = true;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = com.google.appengine.entity.Entity.EntityProto.getDefaultInstance();
        return this;
      }
      
      // required int64 update_id = 2;
      public boolean hasUpdateId() {
        return result.hasUpdateId();
      }
      public long getUpdateId() {
        return result.getUpdateId();
      }
      public Builder setUpdateId(long value) {
        result.hasUpdateId = true;
        result.updateId_ = value;
        return this;
      }
      public Builder clearUpdateId() {
        result.hasUpdateId = false;
        result.updateId_ = 0L;
        return this;
      }
    }
    
    static {
      net.notdot.bdbdatastore.Indexing.getDescriptor();
    }
  }
  
  public static final class EntityKey extends
      com.google.protobuf.GeneratedMessage {
    // Use EntityKey.newBuilder() to construct.
    private EntityKey() {}
    
    private static final EntityKey defaultInstance = new EntityKey();
    public static EntityKey getDefaultInstance() {
      return defaultInstance;
    }
    
    public EntityKey getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_EntityKey_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_EntityKey_fieldAccessorTable;
    }
    
    // required bytes kind = 1;
    private boolean hasKind;
    private com.google.protobuf.ByteString kind_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKind() { return hasKind; }
    public com.google.protobuf.ByteString getKind() { return kind_; }
    
    // optional .com.google.appengine.entity.Path path = 2;
    private boolean hasPath;
    private com.google.appengine.entity.Entity.Path path_ = com.google.appengine.entity.Entity.Path.getDefaultInstance();
    public boolean hasPath() { return hasPath; }
    public com.google.appengine.entity.Entity.Path getPath() { return path_; }
    
    public static net.notdot.bdbdatastore.Indexing.EntityKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.EntityKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.notdot.bdbdatastore.Indexing.EntityKey prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.notdot.bdbdatastore.Indexing.EntityKey.newBuilder()
      private Builder() {}
      
      net.notdot.bdbdatastore.Indexing.EntityKey result = new net.notdot.bdbdatastore.Indexing.EntityKey();
      
      @Override
      protected net.notdot.bdbdatastore.Indexing.EntityKey internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.notdot.bdbdatastore.Indexing.EntityKey();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.notdot.bdbdatastore.Indexing.EntityKey.getDescriptor();
      }
      
      public net.notdot.bdbdatastore.Indexing.EntityKey getDefaultInstanceForType() {
        return net.notdot.bdbdatastore.Indexing.EntityKey.getDefaultInstance();
      }
      
      public net.notdot.bdbdatastore.Indexing.EntityKey build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.notdot.bdbdatastore.Indexing.EntityKey buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.notdot.bdbdatastore.Indexing.EntityKey buildPartial() {
        net.notdot.bdbdatastore.Indexing.EntityKey returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required bytes kind = 1;
      public boolean hasKind() {
        return result.hasKind();
      }
      public com.google.protobuf.ByteString getKind() {
        return result.getKind();
      }
      public Builder setKind(com.google.protobuf.ByteString value) {
        result.hasKind = true;
        result.kind_ = value;
        return this;
      }
      public Builder clearKind() {
        result.hasKind = false;
        result.kind_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // optional .com.google.appengine.entity.Path path = 2;
      public boolean hasPath() {
        return result.hasPath();
      }
      public com.google.appengine.entity.Entity.Path getPath() {
        return result.getPath();
      }
      public Builder setPath(com.google.appengine.entity.Entity.Path value) {
        result.hasPath = true;
        result.path_ = value;
        return this;
      }
      public Builder setPath(com.google.appengine.entity.Entity.Path.Builder builderForValue) {
        result.hasPath = true;
        result.path_ = builderForValue.build();
        return this;
      }
      public Builder mergePath(com.google.appengine.entity.Entity.Path value) {
        if (result.hasPath() &&
            result.path_ != com.google.appengine.entity.Entity.Path.getDefaultInstance()) {
          result.path_ =
            com.google.appengine.entity.Entity.Path.newBuilder(result.path_).mergeFrom(value).buildPartial();
        } else {
          result.path_ = value;
        }
        result.hasPath = true;
        return this;
      }
      public Builder clearPath() {
        result.hasPath = false;
        result.path_ = com.google.appengine.entity.Entity.Path.getDefaultInstance();
        return this;
      }
    }
    
    static {
      net.notdot.bdbdatastore.Indexing.getDescriptor();
    }
  }
  
  public static final class PropertyIndexKey extends
      com.google.protobuf.GeneratedMessage {
    // Use PropertyIndexKey.newBuilder() to construct.
    private PropertyIndexKey() {}
    
    private static final PropertyIndexKey defaultInstance = new PropertyIndexKey();
    public static PropertyIndexKey getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyIndexKey getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_PropertyIndexKey_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_PropertyIndexKey_fieldAccessorTable;
    }
    
    // required bytes kind = 1;
    private boolean hasKind;
    private com.google.protobuf.ByteString kind_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKind() { return hasKind; }
    public com.google.protobuf.ByteString getKind() { return kind_; }
    
    // required bytes name = 2;
    private boolean hasName;
    private com.google.protobuf.ByteString name_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasName() { return hasName; }
    public com.google.protobuf.ByteString getName() { return name_; }
    
    // optional .com.google.appengine.entity.PropertyValue value = 3;
    private boolean hasValue;
    private com.google.appengine.entity.Entity.PropertyValue value_ = com.google.appengine.entity.Entity.PropertyValue.getDefaultInstance();
    public boolean hasValue() { return hasValue; }
    public com.google.appengine.entity.Entity.PropertyValue getValue() { return value_; }
    
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.PropertyIndexKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.notdot.bdbdatastore.Indexing.PropertyIndexKey prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.notdot.bdbdatastore.Indexing.PropertyIndexKey.newBuilder()
      private Builder() {}
      
      net.notdot.bdbdatastore.Indexing.PropertyIndexKey result = new net.notdot.bdbdatastore.Indexing.PropertyIndexKey();
      
      @Override
      protected net.notdot.bdbdatastore.Indexing.PropertyIndexKey internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.notdot.bdbdatastore.Indexing.PropertyIndexKey();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.notdot.bdbdatastore.Indexing.PropertyIndexKey.getDescriptor();
      }
      
      public net.notdot.bdbdatastore.Indexing.PropertyIndexKey getDefaultInstanceForType() {
        return net.notdot.bdbdatastore.Indexing.PropertyIndexKey.getDefaultInstance();
      }
      
      public net.notdot.bdbdatastore.Indexing.PropertyIndexKey build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.notdot.bdbdatastore.Indexing.PropertyIndexKey buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.notdot.bdbdatastore.Indexing.PropertyIndexKey buildPartial() {
        net.notdot.bdbdatastore.Indexing.PropertyIndexKey returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required bytes kind = 1;
      public boolean hasKind() {
        return result.hasKind();
      }
      public com.google.protobuf.ByteString getKind() {
        return result.getKind();
      }
      public Builder setKind(com.google.protobuf.ByteString value) {
        result.hasKind = true;
        result.kind_ = value;
        return this;
      }
      public Builder clearKind() {
        result.hasKind = false;
        result.kind_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // required bytes name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public com.google.protobuf.ByteString getName() {
        return result.getName();
      }
      public Builder setName(com.google.protobuf.ByteString value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // optional .com.google.appengine.entity.PropertyValue value = 3;
      public boolean hasValue() {
        return result.hasValue();
      }
      public com.google.appengine.entity.Entity.PropertyValue getValue() {
        return result.getValue();
      }
      public Builder setValue(com.google.appengine.entity.Entity.PropertyValue value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder setValue(com.google.appengine.entity.Entity.PropertyValue.Builder builderForValue) {
        result.hasValue = true;
        result.value_ = builderForValue.build();
        return this;
      }
      public Builder mergeValue(com.google.appengine.entity.Entity.PropertyValue value) {
        if (result.hasValue() &&
            result.value_ != com.google.appengine.entity.Entity.PropertyValue.getDefaultInstance()) {
          result.value_ =
            com.google.appengine.entity.Entity.PropertyValue.newBuilder(result.value_).mergeFrom(value).buildPartial();
        } else {
          result.value_ = value;
        }
        result.hasValue = true;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = com.google.appengine.entity.Entity.PropertyValue.getDefaultInstance();
        return this;
      }
    }
    
    static {
      net.notdot.bdbdatastore.Indexing.getDescriptor();
    }
  }
  
  public static final class CompositeIndexKey extends
      com.google.protobuf.GeneratedMessage {
    // Use CompositeIndexKey.newBuilder() to construct.
    private CompositeIndexKey() {}
    
    private static final CompositeIndexKey defaultInstance = new CompositeIndexKey();
    public static CompositeIndexKey getDefaultInstance() {
      return defaultInstance;
    }
    
    public CompositeIndexKey getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_CompositeIndexKey_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_CompositeIndexKey_fieldAccessorTable;
    }
    
    // optional .com.google.appengine.entity.Path ancestor = 1;
    private boolean hasAncestor;
    private com.google.appengine.entity.Entity.Path ancestor_ = com.google.appengine.entity.Entity.Path.getDefaultInstance();
    public boolean hasAncestor() { return hasAncestor; }
    public com.google.appengine.entity.Entity.Path getAncestor() { return ancestor_; }
    
    // repeated .com.google.appengine.entity.PropertyValue value = 2;
    private java.util.List<com.google.appengine.entity.Entity.PropertyValue> value_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.appengine.entity.Entity.PropertyValue> getValueList() {
      return value_;
    }
    public int getValueCount() { return value_.size(); }
    public com.google.appengine.entity.Entity.PropertyValue getValue(int index) {
      return value_.get(index);
    }
    
    public static net.notdot.bdbdatastore.Indexing.CompositeIndexKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.CompositeIndexKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.CompositeIndexKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.CompositeIndexKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.CompositeIndexKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.CompositeIndexKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.CompositeIndexKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.CompositeIndexKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.notdot.bdbdatastore.Indexing.CompositeIndexKey prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.notdot.bdbdatastore.Indexing.CompositeIndexKey.newBuilder()
      private Builder() {}
      
      net.notdot.bdbdatastore.Indexing.CompositeIndexKey result = new net.notdot.bdbdatastore.Indexing.CompositeIndexKey();
      
      @Override
      protected net.notdot.bdbdatastore.Indexing.CompositeIndexKey internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.notdot.bdbdatastore.Indexing.CompositeIndexKey();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.notdot.bdbdatastore.Indexing.CompositeIndexKey.getDescriptor();
      }
      
      public net.notdot.bdbdatastore.Indexing.CompositeIndexKey getDefaultInstanceForType() {
        return net.notdot.bdbdatastore.Indexing.CompositeIndexKey.getDefaultInstance();
      }
      
      public net.notdot.bdbdatastore.Indexing.CompositeIndexKey build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.notdot.bdbdatastore.Indexing.CompositeIndexKey buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.notdot.bdbdatastore.Indexing.CompositeIndexKey buildPartial() {
        if (result.value_ != java.util.Collections.EMPTY_LIST) {
          result.value_ =
            java.util.Collections.unmodifiableList(result.value_);
        }
        net.notdot.bdbdatastore.Indexing.CompositeIndexKey returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional .com.google.appengine.entity.Path ancestor = 1;
      public boolean hasAncestor() {
        return result.hasAncestor();
      }
      public com.google.appengine.entity.Entity.Path getAncestor() {
        return result.getAncestor();
      }
      public Builder setAncestor(com.google.appengine.entity.Entity.Path value) {
        result.hasAncestor = true;
        result.ancestor_ = value;
        return this;
      }
      public Builder setAncestor(com.google.appengine.entity.Entity.Path.Builder builderForValue) {
        result.hasAncestor = true;
        result.ancestor_ = builderForValue.build();
        return this;
      }
      public Builder mergeAncestor(com.google.appengine.entity.Entity.Path value) {
        if (result.hasAncestor() &&
            result.ancestor_ != com.google.appengine.entity.Entity.Path.getDefaultInstance()) {
          result.ancestor_ =
            com.google.appengine.entity.Entity.Path.newBuilder(result.ancestor_).mergeFrom(value).buildPartial();
        } else {
          result.ancestor_ = value;
        }
        result.hasAncestor = true;
        return this;
      }
      public Builder clearAncestor() {
        result.hasAncestor = false;
        result.ancestor_ = com.google.appengine.entity.Entity.Path.getDefaultInstance();
        return this;
      }
      
      // repeated .com.google.appengine.entity.PropertyValue value = 2;
      public java.util.List<com.google.appengine.entity.Entity.PropertyValue> getValueList() {
        return java.util.Collections.unmodifiableList(result.value_);
      }
      public int getValueCount() {
        return result.getValueCount();
      }
      public com.google.appengine.entity.Entity.PropertyValue getValue(int index) {
        return result.getValue(index);
      }
      public Builder setValue(int index, com.google.appengine.entity.Entity.PropertyValue value) {
        result.value_.set(index, value);
        return this;
      }
      public Builder setValue(int index, com.google.appengine.entity.Entity.PropertyValue.Builder builderForValue) {
        result.value_.set(index, builderForValue.build());
        return this;
      }
      public Builder addValue(com.google.appengine.entity.Entity.PropertyValue value) {
        if (result.value_.isEmpty()) {
          result.value_ = new java.util.ArrayList<com.google.appengine.entity.Entity.PropertyValue>();
        }
        result.value_.add(value);
        return this;
      }
      public Builder addValue(com.google.appengine.entity.Entity.PropertyValue.Builder builderForValue) {
        if (result.value_.isEmpty()) {
          result.value_ = new java.util.ArrayList<com.google.appengine.entity.Entity.PropertyValue>();
        }
        result.value_.add(builderForValue.build());
        return this;
      }
      public Builder addAllValue(
          java.lang.Iterable<? extends com.google.appengine.entity.Entity.PropertyValue> values) {
        if (result.value_.isEmpty()) {
          result.value_ = new java.util.ArrayList<com.google.appengine.entity.Entity.PropertyValue>();
        }
        super.addAll(values, result.value_);
        return this;
      }
      public Builder clearValue() {
        result.value_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.notdot.bdbdatastore.Indexing.getDescriptor();
    }
  }
  
  public static final class IndexList extends
      com.google.protobuf.GeneratedMessage {
    // Use IndexList.newBuilder() to construct.
    private IndexList() {}
    
    private static final IndexList defaultInstance = new IndexList();
    public static IndexList getDefaultInstance() {
      return defaultInstance;
    }
    
    public IndexList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_IndexList_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.notdot.bdbdatastore.Indexing.internal_static_net_notdot_bdbdatastore_IndexList_fieldAccessorTable;
    }
    
    // repeated .com.google.appengine.entity.CompositeIndex index = 1;
    private java.util.List<com.google.appengine.entity.Entity.CompositeIndex> index_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.appengine.entity.Entity.CompositeIndex> getIndexList() {
      return index_;
    }
    public int getIndexCount() { return index_.size(); }
    public com.google.appengine.entity.Entity.CompositeIndex getIndex(int index) {
      return index_.get(index);
    }
    
    // required int64 next_id = 2;
    private boolean hasNextId;
    private long nextId_ = 0L;
    public boolean hasNextId() { return hasNextId; }
    public long getNextId() { return nextId_; }
    
    public static net.notdot.bdbdatastore.Indexing.IndexList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.IndexList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.IndexList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.IndexList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.IndexList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.IndexList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.IndexList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.notdot.bdbdatastore.Indexing.IndexList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.notdot.bdbdatastore.Indexing.IndexList prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.notdot.bdbdatastore.Indexing.IndexList.newBuilder()
      private Builder() {}
      
      net.notdot.bdbdatastore.Indexing.IndexList result = new net.notdot.bdbdatastore.Indexing.IndexList();
      
      @Override
      protected net.notdot.bdbdatastore.Indexing.IndexList internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.notdot.bdbdatastore.Indexing.IndexList();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.notdot.bdbdatastore.Indexing.IndexList.getDescriptor();
      }
      
      public net.notdot.bdbdatastore.Indexing.IndexList getDefaultInstanceForType() {
        return net.notdot.bdbdatastore.Indexing.IndexList.getDefaultInstance();
      }
      
      public net.notdot.bdbdatastore.Indexing.IndexList build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.notdot.bdbdatastore.Indexing.IndexList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.notdot.bdbdatastore.Indexing.IndexList buildPartial() {
        if (result.index_ != java.util.Collections.EMPTY_LIST) {
          result.index_ =
            java.util.Collections.unmodifiableList(result.index_);
        }
        net.notdot.bdbdatastore.Indexing.IndexList returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .com.google.appengine.entity.CompositeIndex index = 1;
      public java.util.List<com.google.appengine.entity.Entity.CompositeIndex> getIndexList() {
        return java.util.Collections.unmodifiableList(result.index_);
      }
      public int getIndexCount() {
        return result.getIndexCount();
      }
      public com.google.appengine.entity.Entity.CompositeIndex getIndex(int index) {
        return result.getIndex(index);
      }
      public Builder setIndex(int index, com.google.appengine.entity.Entity.CompositeIndex value) {
        result.index_.set(index, value);
        return this;
      }
      public Builder setIndex(int index, com.google.appengine.entity.Entity.CompositeIndex.Builder builderForValue) {
        result.index_.set(index, builderForValue.build());
        return this;
      }
      public Builder addIndex(com.google.appengine.entity.Entity.CompositeIndex value) {
        if (result.index_.isEmpty()) {
          result.index_ = new java.util.ArrayList<com.google.appengine.entity.Entity.CompositeIndex>();
        }
        result.index_.add(value);
        return this;
      }
      public Builder addIndex(com.google.appengine.entity.Entity.CompositeIndex.Builder builderForValue) {
        if (result.index_.isEmpty()) {
          result.index_ = new java.util.ArrayList<com.google.appengine.entity.Entity.CompositeIndex>();
        }
        result.index_.add(builderForValue.build());
        return this;
      }
      public Builder addAllIndex(
          java.lang.Iterable<? extends com.google.appengine.entity.Entity.CompositeIndex> values) {
        if (result.index_.isEmpty()) {
          result.index_ = new java.util.ArrayList<com.google.appengine.entity.Entity.CompositeIndex>();
        }
        super.addAll(values, result.index_);
        return this;
      }
      public Builder clearIndex() {
        result.index_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required int64 next_id = 2;
      public boolean hasNextId() {
        return result.hasNextId();
      }
      public long getNextId() {
        return result.getNextId();
      }
      public Builder setNextId(long value) {
        result.hasNextId = true;
        result.nextId_ = value;
        return this;
      }
      public Builder clearNextId() {
        result.hasNextId = false;
        result.nextId_ = 0L;
        return this;
      }
    }
    
    static {
      net.notdot.bdbdatastore.Indexing.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_notdot_bdbdatastore_EntityData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_notdot_bdbdatastore_EntityData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_notdot_bdbdatastore_EntityKey_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_notdot_bdbdatastore_EntityKey_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_notdot_bdbdatastore_PropertyIndexKey_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_notdot_bdbdatastore_PropertyIndexKey_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_notdot_bdbdatastore_CompositeIndexKey_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_notdot_bdbdatastore_CompositeIndexKey_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_notdot_bdbdatastore_IndexList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_notdot_bdbdatastore_IndexList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\016indexing.proto\022\027net.notdot.bdbdatastor" +
      "e\032\014entity.proto\032\016api_base.proto\"W\n\nEntit" +
      "yData\0226\n\004data\030\001 \002(\0132(.com.google.appengi" +
      "ne.entity.EntityProto\022\021\n\tupdate_id\030\002 \002(\003" +
      "\"J\n\tEntityKey\022\014\n\004kind\030\001 \002(\014\022/\n\004path\030\002 \001(" +
      "\0132!.com.google.appengine.entity.Path\"i\n\020" +
      "PropertyIndexKey\022\014\n\004kind\030\001 \002(\014\022\014\n\004name\030\002" +
      " \002(\014\0229\n\005value\030\003 \001(\0132*.com.google.appengi" +
      "ne.entity.PropertyValue\"\203\001\n\021CompositeInd" +
      "exKey\0223\n\010ancestor\030\001 \001(\0132!.com.google.app" +
      "engine.entity.Path\0229\n\005value\030\002 \003(\0132*.com." +
      "google.appengine.entity.PropertyValue\"X\n" +
      "\tIndexList\022:\n\005index\030\001 \003(\0132+.com.google.a" +
      "ppengine.entity.CompositeIndex\022\017\n\007next_i" +
      "d\030\002 \002(\003";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_notdot_bdbdatastore_EntityData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_notdot_bdbdatastore_EntityData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_notdot_bdbdatastore_EntityData_descriptor,
              new java.lang.String[] { "Data", "UpdateId", },
              net.notdot.bdbdatastore.Indexing.EntityData.class,
              net.notdot.bdbdatastore.Indexing.EntityData.Builder.class);
          internal_static_net_notdot_bdbdatastore_EntityKey_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_notdot_bdbdatastore_EntityKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_notdot_bdbdatastore_EntityKey_descriptor,
              new java.lang.String[] { "Kind", "Path", },
              net.notdot.bdbdatastore.Indexing.EntityKey.class,
              net.notdot.bdbdatastore.Indexing.EntityKey.Builder.class);
          internal_static_net_notdot_bdbdatastore_PropertyIndexKey_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_net_notdot_bdbdatastore_PropertyIndexKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_notdot_bdbdatastore_PropertyIndexKey_descriptor,
              new java.lang.String[] { "Kind", "Name", "Value", },
              net.notdot.bdbdatastore.Indexing.PropertyIndexKey.class,
              net.notdot.bdbdatastore.Indexing.PropertyIndexKey.Builder.class);
          internal_static_net_notdot_bdbdatastore_CompositeIndexKey_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_net_notdot_bdbdatastore_CompositeIndexKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_notdot_bdbdatastore_CompositeIndexKey_descriptor,
              new java.lang.String[] { "Ancestor", "Value", },
              net.notdot.bdbdatastore.Indexing.CompositeIndexKey.class,
              net.notdot.bdbdatastore.Indexing.CompositeIndexKey.Builder.class);
          internal_static_net_notdot_bdbdatastore_IndexList_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_net_notdot_bdbdatastore_IndexList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_notdot_bdbdatastore_IndexList_descriptor,
              new java.lang.String[] { "Index", "NextId", },
              net.notdot.bdbdatastore.Indexing.IndexList.class,
              net.notdot.bdbdatastore.Indexing.IndexList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.appengine.entity.Entity.getDescriptor(),
          com.google.appengine.base.ApiBase.getDescriptor(),
        }, assigner);
  }
}
